name: 'Build LaTex Document'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: Tectonic Cache
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-
      - uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tectonic
        run: cd paper && tectonic Bump10MSun.tex
      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: Bump10MSun
          path: paper/Bump10MSun.pdf
      - name: Push PDF
        run: |
            git checkout --orphan ${GITHUB_REF##*/}-pdf
            git rm -rf .
            cd paper
            git add -f Bump10MSun.pdf
            git -c user.name="paper-builder" -c user.email="paper-builder" commit -m "Update PDF"
            git push -q -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${GITHUB_REF##*/}-pdf
